name: myenv
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.11.3
  - ipykernel=6.19.2
  - ipython=8.12.0
  - pip=23.0.1
  - pip:
      - lightning==2.0.2
      - hydra-core==1.3.2
      - matplotlib==3.7.1
      - flask==2.3.2
      - librosa==0.10.0.post2
      - numpy==1.24.3
      - requests==2.30.0
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - tensorboard==2.13.0
      - pandas==2.0.1
      - seaborn==0.12.2
      - dataframe_image==0.1.11
